version: 0.2
env:
  shell: bash
phases:
  install:
    commands:
      - git clone https://github.com/aws/aws-elastic-beanstalk-cli-setup.git
      - apt update
      - apt install build-essential zlib1g-dev libncurses5-dev libgdbm-dev libnss3-dev libssl-dev libreadline-dev libffi-dev curl
      - tar -xf Python-3.?.?.tar.xz
      - cd Python-3.*
      - ./configure
      - python --version
      - python ./aws-elastic-beanstalk-cli-setup/scripts/ebcli_installer.py
      - eb --version
      - npm i npm@latest -g
      - npm install
  build:
    commands:
      #- npm run build
      - npm run test unit
  post_build:
    commands:
      - |
        if [ "${NODE_ENV}" = "development" ] ; then 
          aws configure set aws_access_key_id ${AWS_ACCESS_KEY}; aws configure set aws_secret_access_key ${AWS_SECRET_KEY}; aws configure set default.region ${AWS_REGION}
          yes n | eb init --platform "arn:aws:elasticbeanstalk:ap-southeast-2::platform/Node.js 14 running on 64bit Amazon Linux 2/5.4.9" --region ap-southeast-2 bpdev
          eb use bpdev-env
          eb setenv GOOGLE_MAPS_API_KEY=${GOOGLE_MAPS_API_KEY} AWS_REGION=${AWS_REGION} AWS_S3_BUCKET_URL=${AWS_S3_BUCKET_URL} AWS_S3_BUCKET=${AWS_S3_BUCKET} NODE_ENV=${NODE_ENV} PORT=${PORT} APP_NAME=${APP_NAME} AWS_SES_ACCESS_KEY=${AWS_SES_ACCESS_KEY} AWS_SES_SECRET_KEY=${AWS_SES_SECRET_KEY} EMAIL_DEFAULT_SENDER=${EMAIL_DEFAULT_SENDER} AWS_COGNITO_POOL_ID=${AWS_COGNITO_POOL_ID} AWS_COGNITO_APP_CLIENT_ID=${AWS_COGNITO_APP_CLIENT_ID} POSTGRES_HOST=${POSTGRES_HOST} POSTGRES_PORT=${POSTGRES_PORT} POSTGRES_USERNAME=${POSTGRES_USERNAME} POSTGRES_PASSWORD=${POSTGRES_PASSWORD} POSTGRES_DATABASE=${POSTGRES_DATABASE}
        fi
      - |
        if [ "${NODE_ENV}" = "staging" ] ; then
          aws configure set aws_access_key_id ${AWS_ACCESS_KEY}; aws configure set aws_secret_access_key ${AWS_SECRET_KEY}; aws configure set default.region ${AWS_REGION}
          yes n | eb init --platform "arn:aws:elasticbeanstalk:ap-southeast-2::platform/Node.js 14 running on 64bit Amazon Linux 2/5.4.9" --region ap-southeast-2 bpstaging
          eb use Bpstaging-env
          eb setenv GOOGLE_MAPS_API_KEY=${GOOGLE_MAPS_API_KEY} AWS_REGION=${AWS_REGION} AWS_S3_BUCKET_URL=${AWS_S3_BUCKET_URL} AWS_S3_BUCKET=${AWS_S3_BUCKET} NODE_ENV=${NODE_ENV} PORT=${PORT} APP_NAME=${APP_NAME} AWS_SES_ACCESS_KEY=${AWS_SES_ACCESS_KEY} AWS_SES_SECRET_KEY=${AWS_SES_SECRET_KEY} EMAIL_DEFAULT_SENDER=${EMAIL_DEFAULT_SENDER} AWS_COGNITO_POOL_ID=${AWS_COGNITO_POOL_ID} AWS_COGNITO_APP_CLIENT_ID=${AWS_COGNITO_APP_CLIENT_ID} POSTGRES_HOST=${POSTGRES_HOST} POSTGRES_PORT=${POSTGRES_PORT} POSTGRES_USERNAME=${POSTGRES_USERNAME} POSTGRES_PASSWORD=${POSTGRES_PASSWORD} POSTGRES_DATABASE=${POSTGRES_DATABASE}
        fi
      - aws configure list